# Use postgres/example user/password credentials
version: '3.9'

services:

  psql-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #   - type: tmpfs
    #     target: /dev/shm
    #     tmpfs:
    #       size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Changeme+123

  psql-admin:
    # --- Credentials ---
    # System: PostgreSQL
    # Server: psql-db
    # Username: postgres
    # Password: Changeme+123
    # Database: tutorial-db-01
    image: adminer
    restart: always
    ports:
      - 6969:8080
      # <host>:<container>
